#include "hid.h"
#include <setupapi.h>
#include <hidsdi.h>
#include <stdio.h>

#pragma comment(lib, "hid.lib")
#pragma comment(lib, "setupapi.lib")

#define VENDOR_ID  0xFEED
#define PRODUCT_ID 0x0000


//  this method checks every single device connected to the pc for the
//  keyboard, comparing all the attributes and required datas (i think)
//  if everythings right, in terms of found the keyboard, it gets prepared
//  and returned as HANDLE. this method got completly generated by ai, as
//  currently its still really hard for me to understand the concept of hids
//  and the therefore needed librarys in C. but i am looking forward to completly 
//  learn it and replace this shity method.

HANDLE hid_open(void) {
    GUID hidGuid;
    HidD_GetHidGuid(&hidGuid);

    HDEVINFO deviceInfo = SetupDiGetClassDevs(
        &hidGuid, NULL, NULL, DIGCF_PRESENT | DIGCF_DEVICEINTERFACE
    );

    if (deviceInfo == INVALID_HANDLE_VALUE)
        return NULL;

    SP_DEVICE_INTERFACE_DATA deviceInterfaceData;
    deviceInterfaceData.cbSize = sizeof(deviceInterfaceData);

    for (DWORD i = 0; SetupDiEnumDeviceInterfaces(
            deviceInfo, NULL, &hidGuid, i, &deviceInterfaceData); i++) {

        DWORD requiredSize = 0;
        SetupDiGetDeviceInterfaceDetail(
            deviceInfo, &deviceInterfaceData, NULL, 0, &requiredSize, NULL
        );

        PSP_DEVICE_INTERFACE_DETAIL_DATA detailData =
            (PSP_DEVICE_INTERFACE_DETAIL_DATA)malloc(requiredSize);
        detailData->cbSize = sizeof(SP_DEVICE_INTERFACE_DETAIL_DATA);

        if (!SetupDiGetDeviceInterfaceDetail(
                deviceInfo, &deviceInterfaceData, detailData,
                requiredSize, NULL, NULL)) {
            free(detailData);
            continue;
        }

        HANDLE device = CreateFile(
            detailData->DevicePath,
            GENERIC_READ | GENERIC_WRITE,
            FILE_SHARE_READ | FILE_SHARE_WRITE,
            NULL,
            OPEN_EXISTING,
            FILE_FLAG_OVERLAPPED,
            NULL
        );

        free(detailData);

        if (device == INVALID_HANDLE_VALUE)
            continue;

        HIDD_ATTRIBUTES attributes;
        attributes.Size = sizeof(attributes);

        if (HidD_GetAttributes(device, &attributes)) {
            if (attributes.VendorID == VENDOR_ID &&
                attributes.ProductID == PRODUCT_ID) {
                return device;
            }
        }

        CloseHandle(device);
    }

    return NULL;
}


//  this method just takes the device (keyboard) and reads it hids
//  and returns them in form of a collection of bytes

int hid_read(HANDLE device, uint8_t* buffer) {
    DWORD bytesRead = 0;

    if (!ReadFile(device, buffer, HID_BUFFER_SIZE, &bytesRead, NULL))
        return -1;
    
    return bytesRead;
}


//  this just closes the before created connection to the keyboard
//  after the process is beended and it not anymore needed

void hid_close(HANDLE device) {
    if (device)
        CloseHandle(device);
}